name: Linting

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt
      - name: Python lint
        run: |
          echo "::add-matcher::ruff.json"
          ruff check custom_components/tuya_local
          echo "::remove-matcher owner=ruff::"
      - name: Python include order
        run: ruff check --select I --diff .
      - name: Python coding style
        run: ruff format --check --diff .
      - name: YAML lint
        run: |
          echo "::add-matcher::yamllint.json"
          yamllint -f parsable custom_components/tuya_local/devices
          echo "::remove-matcher owner=yamllint::"
